name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  path_provider: ^2.0.5
  geolocator: ^13.0.1
  intl: ^0.17.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true
